### ISSUE TITLE
请问一下使用的是什么方式实现的并发？

### ISSUE THREAD

**Issue by Hanwn** [codetalks-new/csite#1]
多线程还是多进程，在代码中没有发现fork和pthread，所以想问一下使用的是什么技术实现的并发？

**Comment by codetalks-new** [comment]
> 多线程还是多进程，在代码中没有发现fork和pthread，所以想问一下使用的是什么技术实现的并发？

现在还没有实现并发, 而且也没有复用连接, 后面慢慢完善吧,当作一个学习处理处理模式的 demo
